# Generated by Django 3.1.7 on 2021-03-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='albums/images/')),
                ('logo', models.ImageField(null=True, upload_to='page/images/')),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
