# Generated by Django 3.1.7 on 2021-03-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='imagen',
        ),
        migrations.AddField(
            model_name='page',
            name='titul',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
