# Generated by Django 3.1.7 on 2021-03-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default=False)),
                ('ingreso', models.CharField(max_length=50, null=True)),
                ('tiempo', models.CharField(max_length=50, null=True)),
                ('boton1', models.CharField(max_length=50, null=True)),
                ('boton2', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
