# Generated by Django 3.1.7 on 2021-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
