# Generated by Django 3.1.7 on 2021-03-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='username',
            new_name='name',
        ),
    ]
